-- 6
-- FIND THE ADDRESS OF THE CUSTOMER BY ADDRESS_CODE
SELECT CUSTOMER_ID,ADDRESS_1,CITY,STATE_PROVINCE,COUNTRY
FROM locations INNER JOIN customer
WHERE CUSTOMER_ID = "CUSTOMER_ID";-- NEED AN INPUT FROM THE USER

-- FIND THE PURCHASE HISTORY OF THE CUSTOMER
SELECT CUSTOMER_ID,ORDER_ID,TOTAL_VALUE,ORDER_DATE
FROM order_information
WHERE CUSTOMER_ID = "CUSTOMER_ID";-- NEED AN INPUT FROM THE USER

-- FIND THE DETAILED INFORMATION FOR A SPECIFIC ORDER(CAN BE USED TO FIND THE ORDER INFORMATION)
SELECT ORDER_ID,ONLINE_STORE_ID,PRODUCT_ID,BUY_NUM,UNIT_SALE_PRICE,TOTAL_SALE_PRICE
FROM order_list
WHERE ORDER_ID = "ORDER_ID";

-- FIND THE TOTAL CONSUMPTION FOR A CUSTOMER
SELECT SUM(TOTAL_VALUE)
FROM order_information
WHERE CUSTOMER_ID = "CUSTOMER_ID";

-- 7
-- the preference of different goods for customers of different gendor
SELECT PRODUCT_ID,COUNT(PRODUCT_ID)
FROM order_list
WHERE order_list.CUSTOMER_ID IN(
SELECT customer.CUSTOMER_ID
FROM customer
WHERE CUSTOMER_GENDER = "female"
)
GROUP BY PRODUCT_ID


