SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE project;

SELECT
    COUNT(*) as GENDER_NUM, SUM(TOTAL_VALUE) as TOTAL_CONSUMPTION, AVG(TOTAL_VALUE) as AVERAGE_CONSUMPTION
FROM
    `customer` t1 LEFT JOIN `order_information` t2 ON t1.ORDER_LIST_ID = t2.ORDER_ID
GROUP BY
    CUSTOMER_GENDER;

SELECT 
    COUNT(*) as STATE_NUM, SUM(TOTAL_VALUE) as TOTAL_CONSUMPTION, AVG(TOTAL_VALUE) as AVERAGE_CONSUMPTION
FROM
    (`customer` t1 LEFT JOIN `order_information` t2 ON t1.ORDER_LIST_ID = t2.ORDER_ID)
    LEFT JOIN `locations` t3 ON t1.CUSTOMER_LOCATION_ID = t3.LOCATION_ID
GROUP BY STATE_PROVINCE;

